#!/usr/bin/env python
# Very simple <diff -u file1 file2> wrapper
# Jun. 24, 2015 haishanh

from __future__ import print_function
import sys
import os.path
import subprocess
import re

color = {"default":"\033[0m", "red":"\033[31m", "green":"\033[32m"}

class shSession():
    def __init__(self):
        self._output = ''
    def sendcmd(self, cmd):
        x = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
        self._output = x.stdout.read()
    def output(self):
        return self._output

def usage_exit():
    print('Usage:')
    print('%s <file1> <file2>' %(' ' * 4 + __file__))
    exit(1)

if __name__ == '__main__':
    sh = shSession()
    if len(sys.argv) <= 2:
        usage_exit()
    if not os.path.isfile(sys.argv[1]):
        usage_exit()
    if not os.path.isfile(sys.argv[2]):
        usage_exit()
    sh.sendcmd('diff -u ' + sys.argv[1] +' ' + sys.argv[2])
    add = re.compile(r'^\+{1,3}.*')
    minus = re.compile(r'^\-{1,3}.*')
    for line in sh.output().splitlines():
        if add.match(line):
            line = color['green'] + line + color['default']
        elif minus.match(line):
            line = color['red'] + line + color['default']
        print(line)
