#!/bin/bash

MONODIR="$HOME/t"
TARGET="dependencies"

random=$(date +"%y%m%d%H%M%S")
TMP="/tmp/pkg-${random}.json"


install_if_notexist()
{
  local pkg=$1
  local pkgname=$(echo $pkg | sed 's/@.*//')
  local ret=$(grep "\"${pkgname}\":" package.json)
  if [ ! -z "$ret" ]; then
    echo "$pkg already exist"
  else
    npm install --save $pkg
  fi

  ret=$(grep "\"${pkgname}\":" package.json)
  ret=$(echo "$ret" | sed 's/,$//')
  if [ -n "$ret" ]; then
    echo -n "${ret}," >> $TMP
  fi
}

remove_trailing_comma()
{
  local f=$1
  local tmp="${f}__2"

  sed 's/,$//' $f > $tmp
  cat $tmp > $f
  rm -rf $tmp
}

install_all()
{
  local num=$#
  local i=0
  echo "{" > $TMP
  for pkg in $@; do
    i=$(( $i + 1 ))
    install_if_notexist $pkg
  done
  remove_trailing_comma $TMP
  echo "}" >> $TMP
}

[ -z $1 ] && exit 0
if [ "$1" != "install" ] || [ "$1" != "i" ]; then
  shift
else
  exit 0
fi


if [ "$1" == "-D" ] || [ "$1" == "--save-dev" ]; then
  TARGET="devDependencies"
  shift
elif [ "$1" == "-S" ] || [ "$1" == "--save" ]; then
  shift
fi

DIR=$PWD
cd $MONODIR
install_all $@

cat $TMP

cd $DIR
pkgupdate.js package.json $TMP $TARGET
rm -rf $TMP
